#!/usr/bin/env bash
[ -z "$DEBUG" ] && DEBUG="0"

debug() {
    [ "$DEBUG" -eq "1" ] && return 0
    return 1
}

d() {
    debug && echo "debug: $*" >&2
}

e() {
    echo "error: $*" >&2
}

w() {
    e "warn: $*" >&2
}
