#!/usr/bin/env bash

echo "
Synsei 0.2 - Easily manage synaptics configurations

Usage: synsei <action> [arg1 arg2 ...]

Actions:

help                      - Displays help page
edit <profile> [editor]   - Edits a profile with \$EDITOR or [editor]
list                      - Lists all loadable profiles
load <profile>            - Loads a profile into use
save <profile>            - Saves the current config into a profile
delete <profile>          - Deletes a profile
view [profile]            - Views a profile's config, otherwise views
                            current synclient config
"
