#!/usr/bin/env bash
source functions
echo "Synsei 0.1 - Easily manage synaptics configurations"
echo "Author: Chris Sivanich <csivanich@gmail.com>"
echo "USAGE: synsei action [arg1,arg2...]"
echo "ACTIONS: $(list_actions)"

