#!/usr/bin/env bash
if [ -z "$1" ]; then
    echo "No save file specified" >&2
    exit 1
fi

FILE="$1"
if [ ! -e "$FILE" ]; then
    echo "Creating new save file \"$FILE\""
    touch "$FILE"
fi

if [ ! -w "$FILE" ]; then
    echo "Save file \"$FILE\" is not writable :("
    exit 1
fi

./list | perl -p -e 's/ //g' > "$FILE"

echo "Profile \"$FILE\" saved."
