#!/usr/bin/env bash

source functions
if [ -z "$1" ]; then
    echo "No save file specified" >&2
    exit 1
fi

FILE="$(profile_dir)""$1"
d "Begining save to '$FILE'"
if [ ! -e "$FILE" ]; then
    echo "Creating new profile \"$FILE\""
    touch "$FILE"
fi

if [ ! -w "$FILE" ]; then
    echo "File \"$FILE\" is not writable :("
    exit 1
fi

read_current_profile > "$FILE"
echo "Profile \"$FILE\" saved."
