#!/usr/bin/env bash

source functions

d "View starting"
if [ -z "$1" ]; then
    d "Viewing current values"
    profile=$(read_current_profile)
else
    if profile=$(read_profile "$1");then
        d "Loaded profile '$1'"
    else
        echo "Failed to load profile ($?)" >&2
        exit 1
    fi
fi

echo "$profile" | sed -e 's/=/ .... /g' | sort
